### ISSUE TITLE
There was a problem parsing the package.

### ISSUE THREAD

**Issue by ZendreiPlays117** [SieR-VR/usc-app#13]
![Screenshot_2022-10-02-19-28-34-33](https://user-images.githubusercontent.com/67860120/193451839-d7a4edd7-eaad-48e0-8a68-2f357cbba8a0.jpg)
I wanted to try it out but it won't let me.

**Comment by nick-haoran** [comment]
did you deal with this problem？

> ![Screenshot_2022-10-02-19-28-34-33](https://user-images.githubusercontent.com/67860120/193451839-d7a4edd7-eaad-48e0-8a68-2f357cbba8a0.jpg) I wanted to try it out but it won't let me.

**Comment by FoxMadeline** [comment]
im also getting this issue, tried both packages with no success

**Comment by SieR-VR** [comment]
Sorry for late, what is your android version?

**Comment by ZendreiPlays117** [comment]
Android 8

**Comment by SieR-VR** [comment]
> Android 8

Sorry, usc-app currently supports android version >= 11. I'm working with old android sdk but I can't guarantee when it ends.

**Comment by SieR-VR** [comment]
Close due this issue is about unsupported version of android. If you interested in this project, do pull request for android version <= 10.
