### ISSUE TITLE
Crashing immediately

### ISSUE THREAD

**Issue by ark2000k** [SieR-VR/usc-app#15]
When i open the game, after i allow it to manage my files, the game just crashes. When i open it again, it still crashes. There is no ".usc" under ~/sdcard/.usc/skins directory. It gives no error message

**Comment by SieR-VR** [comment]
Not `.usc` under `/sdcard/.usc/skins`, just `/sdcard`. Maybe auto extraction didn't work.

**Comment by ark2000k** [comment]
Sorry for slow reply, that was a typo, lol. I meant in /sdcard.

**Comment by SieR-VR** [comment]
Did you do manual extraction?

**Comment by ark2000k** [comment]
Hm? Should i manually add the folder of .usc?

**Comment by SieR-VR** [comment]
Yes

**Comment by ark2000k** [comment]
So what files do i add?

**Comment by SieR-VR** [comment]
https://github.com/SieR-VR/usc-app/releases/tag/Assets

**Comment by ark2000k** [comment]
Thank you. So i add it and extract the zip, right? Thanks

**Comment by ark2000k** [comment]
So sdcard/.usc/Essentials/ is correct?

**Comment by SieR-VR** [comment]
No. skins folder and etc should be in ```/sdcard/.usc```. Maybe you need to bring out folders to parent folder.

**Comment by ark2000k** [comment]
Alright, i will try. Thanks

**Comment by ark2000k** [comment]
![Screenshot_2023-04-04-21-43-59-57_7db6921ad48e3f6a68e00267c865ba9e](https://user-images.githubusercontent.com/123225182/229983109-b6642f62-373d-4f0e-8434-041532085533.jpg)

I had this issue for a while, from the old versions, looks like its back again...

**Comment by SieR-VR** [comment]
then extract https://github.com/SieR-VR/usc-default-android/releases/tag/v1.3.0 this to skins folder

**Comment by ark2000k** [comment]
Oh i was always using the lucidwave. Does lucidwave not work? I'll try default

**Comment by ark2000k** [comment]
Default also does not work. I also tried renaming the folder to Default as well, still doesnt work.

**Comment by kuwoh** [comment]
I am having the same problem:
the directory of the skins i put is
/sdcard/.usc/Skins/(skin folder ex: Default, Essentials)
"could not load shaders font.vs and font.fs"

**Comment by georgejeno8** [comment]
For some reason, it seems to only launch for me when the skins folder is at the same level as the .usc folder, instead of inside in the folder.  Is this intended?

**Comment by SieR-VR** [comment]
> For some reason, it seems to only launch for me when the skins folder is at the same level

No, It's not intended. Also, it seems different issue from this. If you want this resolved, please start a new discussion somewhere other than this issue.

**Comment by ark2000k** [comment]
Im still having this issue and I cant fix it. Ive tried 3 skins and it still doesnt work. Could you help?

**Comment by SieR-VR** [comment]
> Im still having this issue and I cant fix it. Ive tried 3 skins and it still doesnt work. Could you help?

At least, I couldn't reproduce those bugs with correct instructions. Can you explain your android phone information?

**Comment by ark2000k** [comment]
Oneplus 7T
Android 12

It also happens on my samsung tablet, too

**Comment by ark2000k** [comment]
Here are both font.vs and font.fs on my device
![Screenshot_2023-10-03-22-08-34-01_3177cc2cf37291944719f629e393766d](https://github.com/SieR-VR/usc-app/assets/123225182/cce8aa9e-6d88-4647-a32a-69dda8b0a3b5)
![Screenshot_2023-10-03-22-08-26-19_3177cc2cf37291944719f629e393766d](https://github.com/SieR-VR/usc-app/assets/123225182/a7002571-8133-4359-a943-1f53e4e71971)
![Screenshot_2023-10-03-22-07-03-07_7db6921ad48e3f6a68e00267c865ba9e](https://github.com/SieR-VR/usc-app/assets/123225182/4b3ecafc-042a-4cb2-b8dc-c174293fceed)

**Comment by ark2000k** [comment]
Hey @SieR-VR, i got it to work using version 0.1.5! The only issue? When i start any song, it crashes after a few seconds of the loading screen. Any way to fix this?
