### ISSUE TITLE
Crashing when song started

### ISSUE THREAD

**Issue by SieR-VR** [SieR-VR/usc-app#17]
Hey @SieR-VR, i got it to work using version 0.1.5! The only issue? When i start any song, it crashes after a few seconds of the loading screen. Any way to fix this?

_Originally posted by @ark2000k in https://github.com/SieR-VR/usc-app/issues/15#issuecomment-1748030476_

**Comment by SieR-VR** [comment]
Was it the default skin?

**Comment by ark2000k** [comment]
Yes. Ive tried nightfall but it crashes once i select it and return to the menu

**Comment by SieR-VR** [comment]
Seems 0.1.5 version issue. Was the original issue (#15) on latest?

**Comment by ark2000k** [comment]
Yes, #15 was on latest, it kept saying that font.fs and font.vs was missing, so i changed to 0.1.5, and it worked.

**Comment by ark2000k** [comment]
It seems like from 0.1.6 onwards it would show 
![Screenshot_2023-10-03-22-08-34-01_3177cc2cf37291944719f629e393766d](https://github.com/SieR-VR/usc-app/assets/123225182/a46d96de-2065-4d69-9705-b4555aa20704)
![Screenshot_2023-10-03-22-08-26-19_3177cc2cf37291944719f629e393766d](https://github.com/SieR-VR/usc-app/assets/123225182/15c1c4eb-1404-42f8-bb8c-59a6b095a0b0)
![Screenshot_2023-10-03-22-07-03-07_7db6921ad48e3f6a68e00267c865ba9e](https://github.com/SieR-VR/usc-app/assets/123225182/84cbd93c-5f7f-425a-9ac6-0451d48d427f)
font.fs and font.vs had issues

**Comment by SieR-VR** [comment]
There was game directory changing (from /data/com.example.unnamed_sdvx_clone to /sdcard/.usc). It is intended, so 0.1.5 wouldn't use /sdcard/.usc assets.

**Comment by SieR-VR** [comment]
Not the file issue, these bugs are from directory mismatching

**Comment by SieR-VR** [comment]
Can you cauture the application permission screen?

**Comment by ark2000k** [comment]
For what version? 

> Can you cauture the application permission screen?

**Comment by SieR-VR** [comment]
> For what version?
> 
> > Can you cauture the application permission screen?

Latest (0.1.17)

**Comment by ark2000k** [comment]
Okay, but ive allowed the permissions for file manage access

**Comment by ark2000k** [comment]
![Uploading Screenshot_2023-10-05-16-54-36-82_ab1359306de43320f9557c797b1c4be5.jpg…]()

**Comment by ark2000k** [comment]
![Screenshot_2023-10-05-16-54-36-82_ab1359306de43320f9557c797b1c4be5](https://github.com/SieR-VR/usc-app/assets/123225182/f3873778-5159-4f0c-9165-495101c670fe)

**Comment by SieR-VR** [comment]
I'm not sure why it can't detect files with "end-user information". Can you use gdb for logging it?

**Comment by ark2000k** [comment]
> I'm not sure why it can't detect files with "end-user information". Can you use gdb for logging it?

Is there a way to fix the issue on version 0.1.5 or do i have to use 0.1.17?

**Comment by SieR-VR** [comment]
For using 0.1.5, you MUST use gdb or ROOT for insert skins and songs

**Comment by ark2000k** [comment]
? whats ROOT? for skins i used FolderV and for songs i got them from oniichan.wtf and connected my phone to my computer, then copied them over

**Comment by SieR-VR** [comment]
https://en.wikipedia.org/wiki/Rooting_(Android)

**Comment by SieR-VR** [comment]
You can't use /sdcard/.usc folder on 0.1.5

**Comment by SieR-VR** [comment]
It was the "feature" from 0.1.7

**Comment by ark2000k** [comment]
Oh rooting. i got confused because you typed it in all caps. yeah i rooted it

**Comment by SieR-VR** [comment]
Was it the rooted android phone?

**Comment by ark2000k** [comment]
android/data/com.example.unnamed_sdvx_clone/files/songs or something like that, i dont have my phone here rn

**Comment by ark2000k** [comment]
> Was it the rooted android phone?

my phone should be rooted, ive switched many phones, i dont remember if this phone is rooted

**Comment by SieR-VR** [comment]
I can't support rooted environment, because there's bunch of reasons for bugs or crashes. If you want to resolve this issue, please open Pull Request for rooted devices.

**Comment by ark2000k** [comment]
> I can't support rooted environment, because there's bunch of reasons for bugs or crashes. If you want to resolve this issue, please open Pull Request for rooted devices.

My tablet, i can say for sure, is not rooted, yet it still doesnt work on 0.1.17

**Comment by ark2000k** [comment]
Ok, i just checked, my phone and my tablet are NOT rooted

**Comment by SieR-VR** [comment]
What the parase "doesn't work" includes:

- My phone wouldn't switch on, so usc-app not working
- I played the football with my phone, so usc-app not working
- With some mistake I deleted android system files, so usc-app not working

**Comment by ark2000k** [comment]
> What the parase "doesn't work" includes:
> 
> * My phone wouldn't switch on, so usc-app not working
> * I played the football with my phone, so usc-app not working
> * With some mistake I deleted android system files, so usc-app not working

On version 0.1.6 and onward: shows "Could not load font.fs and font.vs"

On version 0.1.5: crashes after selecting a song

@SieR-VR

**Comment by ark2000k** [comment]
Hey, do you know how to fix these issues? My phone isnt rooted. Thanks for helping me a lot!

**Comment by ark2000k** [comment]
https://youtube.com/shorts/pEw4eMc_cNo?feature=shared

I recorded a video of it in case it helps :)
