### ISSUE TITLE
How to build in Linux?

### ISSUE THREAD

**Issue by tak2hu** [SieR-VR/usc-app#2]
I'm a newbie in gradle as idk anything and I'm trying to build in **Pop-OS 22.04.**

So I succeeded compiling [usc](https://github.com/Drewol/unnamed-sdvx-clone) _(tho audio doesn't work)_ so I think I already **installed all necessary libraries**.

I already **installed gradle, android-sdk and ndk**. 

Then I tried `./gradlew assembleDebug` and got these errors

```
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

How to get past these errors? thanks!

**Comment by tak2hu** [comment]
Here is the log:
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [22.1.7171670] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir

> Task :app:configureCMakeDebug[arm64-v8a] FAILED
C/C++: debug|arm64-v8a :CMake Error at /home/latitude/Downloads/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake:206 (include):
C/C++: debug|arm64-v8a :  include could not find load file:
C/C++: debug|arm64-v8a :    /usr/lib/android/sdk/ndk/build/cmake/android.toolchain.cmake
C/C++: debug|arm64-v8a :Call Stack (most recent call first):
C/C++: debug|arm64-v8a :  /usr/lib/android-sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
C/C++: debug|arm64-v8a :  CMakeLists.txt:20 (project)
C/C++: debug|arm64-v8a :CMake Error at /home/latitude/Downloads/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake:860 (message):
C/C++: debug|arm64-v8a :  vcpkg install failed.  See logs for more information:
C/C++: debug|arm64-v8a :  /home/latitude/Downloads/usc-app/app/.cxx/Debug/725zd51a/arm64-v8a/vcpkg-manifest-install.log
C/C++: debug|arm64-v8a :Call Stack (most recent call first):
C/C++: debug|arm64-v8a :  /usr/lib/android-sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
C/C++: debug|arm64-v8a :  CMakeLists.txt:20 (project)
C/C++: debug|arm64-v8a :CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
C/C++: debug|arm64-v8a :CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /home/latitude/Downloads/usc-app/app/src/main/cpp/CMakeLists.txt: Build command failed.
  Error while executing process /usr/lib/android-sdk/cmake/3.18.1/bin/cmake with arguments {-H/home/latitude/Downloads/usc-app/app/src/main/cpp -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=30 -DANDROID_PLATFORM=android-30 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/usr/lib/android-sdk/ndk-bundle -DCMAKE_ANDROID_NDK=/usr/lib/android-sdk/ndk-bundle -DCMAKE_MAKE_PROGRAM=/usr/lib/android-sdk/cmake/3.18.1/bin/ninja -DCMAKE_CXX_FLAGS=-std=c++17 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/latitude/Downloads/usc-app/app/build/intermediates/cxx/Debug/725zd51a/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/latitude/Downloads/usc-app/app/build/intermediates/cxx/Debug/725zd51a/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -B/home/latitude/Downloads/usc-app/app/.cxx/Debug/725zd51a/arm64-v8a -GNinja -DANDROID_STL=c++_shared -DANDROID_SYSROOT_PATH=/usr/lib/android-sdk/ndk-bundle/sysroot/usr -DANDROID=1 -DANDROID_NDK_PLATFORM=/usr/lib/android-sdk/ndk-bundle/platforms/android-30/arch-arm64/usr/lib -DCMAKE_TOOLCHAIN_FILE=/home/latitude/Downloads/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/usr/lib/android/sdk/ndk/build/cmake/android.toolchain.cmake -DVCPKG_TARGET_TRIPLET=arm64-android -DANDROID_ABI=arm64-v8a}
  -- Running vcpkg install
  Detecting compiler hash for triplet x64-linux...
  Detecting compiler hash for triplet arm64-android...
  error: while detecting compiler information:
  The log file content at "/home/latitude/Downloads/usc-app/vcpkg/buildtrees/detect_compiler/stdout-arm64-android.log" is:
  -- Configuring arm64-android-rel
  CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
      Command failed: /home/latitude/Downloads/usc-app/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake /home/latitude/Downloads/usc-app/vcpkg/scripts/detect_compiler -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/latitude/Downloads/usc-app/vcpkg/packages/detect_compiler_arm64-android -DCMAKE_MAKE_PROGRAM=/home/latitude/Downloads/usc-app/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/latitude/Downloads/usc-app/vcpkg/scripts/toolchains/android.cmake -DVCPKG_TARGET_TRIPLET=arm64-android -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/latitude/Downloads/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=static -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/latitude/Downloads/usc-app/vcpkg -DZ_VCPKG_ROOT_DIR=/home/latitude/Downloads/usc-app/vcpkg -D_VCPKG_INSTALLED_DIR=/home/latitude/Downloads/usc-app/app/.cxx/Debug/725zd51a/arm64-v8a/vcpkg_installed -DVCPKG_MANIFEST_INSTALL=OFF
      Working Directory: /home/latitude/Downloads/usc-app/vcpkg/buildtrees/detect_compiler/arm64-android-rel
      Error code: 1
      See logs for more information:
        /home/latitude/Downloads/usc-app/vcpkg/buildtrees/detect_compiler/config-arm64-android-rel-CMakeCache.txt.log
        /home/latitude/Downloads/usc-app/vcpkg/buildtrees/detect_compiler/config-arm64-android-rel-out.log
        /home/latitude/Downloads/usc-app/vcpkg/buildtrees/detect_compiler/config-arm64-android-rel-err.log
  
  Call Stack (most recent call first):
    scripts/cmake/vcpkg_configure_cmake.cmake:328 (vcpkg_execute_required_process)
    scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
    scripts/ports.cmake:147 (include)
  
  
  
  error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
  -- Running vcpkg install - failed
  -- Configuring incomplete, errors occurred!
  
  CMake Error at /home/latitude/Downloads/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake:206 (include):
    include could not find load file:
  
      /usr/lib/android/sdk/ndk/build/cmake/android.toolchain.cmake
  Call Stack (most recent call first):
    /usr/lib/android-sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
    CMakeLists.txt:20 (project)
  
  
  CMake Error at /home/latitude/Downloads/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake:860 (message):
    vcpkg install failed.  See logs for more information:
    /home/latitude/Downloads/usc-app/app/.cxx/Debug/725zd51a/arm64-v8a/vcpkg-manifest-install.log
  Call Stack (most recent call first):
    /usr/lib/android-sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
    CMakeLists.txt:20 (project)

**Comment by SieR-VR** [comment]
This project is not for plain linux, just for android. please refer [this repo](https://github.com/Drewol/unnamed-sdvx-clone)

**Comment by wohehehe** [comment]
For me I also face on this problem:
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
WARNING:[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.4.7075529] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir

> Task :app:configureCMakeDebug[arm64-v8a] FAILED
C/C++: debug|arm64-v8a :CMake Error at /Users/dr.feng/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake:860 (message):
C/C++: debug|arm64-v8a :  vcpkg install failed.  See logs for more information:
C/C++: debug|arm64-v8a :  /Users/dr.feng/usc-app/app/.cxx/Debug/5236m5e1/arm64-v8a/vcpkg-manifest-install.log
C/C++: debug|arm64-v8a :Call Stack (most recent call first):
C/C++: debug|arm64-v8a :  /Users/dr.feng/Library/Android/sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
C/C++: debug|arm64-v8a :  CMakeLists.txt:20 (project)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /Users/dr.feng/usc-app/app/src/main/cpp/CMakeLists.txt: Build command failed.
  Error while executing process /Users/dr.feng/Library/Android/sdk/cmake/3.18.1/bin/cmake with arguments {-H/Users/dr.feng/usc-app/app/src/main/cpp -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=30 -DANDROID_PLATFORM=android-30 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/Users/dr.feng/Library/Android/sdk/ndk/21.4.7075529 -DCMAKE_ANDROID_NDK=/Users/dr.feng/Library/Android/sdk/ndk/21.4.7075529 -DCMAKE_MAKE_PROGRAM=/Users/dr.feng/Library/Android/sdk/cmake/3.18.1/bin/ninja -DCMAKE_CXX_FLAGS=-std=c++17 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/dr.feng/usc-app/app/build/intermediates/cxx/Debug/5236m5e1/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/dr.feng/usc-app/app/build/intermediates/cxx/Debug/5236m5e1/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -B/Users/dr.feng/usc-app/app/.cxx/Debug/5236m5e1/arm64-v8a -GNinja -DANDROID_STL=c++_shared -DANDROID_SYSROOT_PATH=/Users/dr.feng/Library/Android/sdk/ndk/21.4.7075529/sysroot/usr -DANDROID=1 -DANDROID_NDK_PLATFORM=/Users/dr.feng/Library/Android/sdk/ndk/21.4.7075529/platforms/android-30/arch-arm64/usr/lib -DCMAKE_TOOLCHAIN_FILE=/Users/dr.feng/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/dr.feng/Library/Android/sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake -DVCPKG_TARGET_TRIPLET=arm64-android -DANDROID_ABI=arm64-v8a}
  -- Running vcpkg install
  Detecting compiler hash for triplet arm64-osx...
  error: while detecting compiler information:
  The log file content at "/Users/dr.feng/usc-app/vcpkg/buildtrees/detect_compiler/stdout-arm64-osx.log" is:
  -- Configuring arm64-osx-rel
  CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
      Command failed: /Users/dr.feng/usc-app/vcpkg/downloads/tools/cmake-3.24.0-osx/cmake-3.24.0-macos-universal/CMake.app/Contents/bin/cmake /Users/dr.feng/usc-app/vcpkg/scripts/detect_compiler -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/dr.feng/usc-app/vcpkg/packages/detect_compiler_arm64-osx -DCMAKE_MAKE_PROGRAM=/Users/dr.feng/usc-app/vcpkg/downloads/tools/ninja/1.10.2-osx/ninja -DCMAKE_SYSTEM_NAME=Darwin -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/dr.feng/usc-app/vcpkg/scripts/toolchains/osx.cmake -DVCPKG_TARGET_TRIPLET=arm64-osx -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/Users/dr.feng/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/Users/dr.feng/usc-app/vcpkg -DZ_VCPKG_ROOT_DIR=/Users/dr.feng/usc-app/vcpkg -D_VCPKG_INSTALLED_DIR=/Users/dr.feng/usc-app/app/.cxx/Debug/5236m5e1/arm64-v8a/vcpkg_installed -DVCPKG_MANIFEST_INSTALL=OFF -DCMAKE_OSX_ARCHITECTURES=arm64
      Working Directory: /Users/dr.feng/usc-app/vcpkg/buildtrees/detect_compiler/arm64-osx-rel
      Error code: 1
      See logs for more information:
        /Users/dr.feng/usc-app/vcpkg/buildtrees/detect_compiler/config-arm64-osx-rel-CMakeCache.txt.log
        /Users/dr.feng/usc-app/vcpkg/buildtrees/detect_compiler/config-arm64-osx-rel-out.log
        /Users/dr.feng/usc-app/vcpkg/buildtrees/detect_compiler/config-arm64-osx-rel-err.log
  
  Call Stack (most recent call first):
    scripts/cmake/vcpkg_configure_cmake.cmake:328 (vcpkg_execute_required_process)
    scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
    scripts/ports.cmake:147 (include)
  
  
  
  error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
  -- Running vcpkg install - failed
  -- Configuring incomplete, errors occurred!
  
  CMake Error at /Users/dr.feng/usc-app/vcpkg/scripts/buildsystems/vcpkg.cmake:860 (message):
    vcpkg install failed.  See logs for more information:
    /Users/dr.feng/usc-app/app/.cxx/Debug/5236m5e1/arm64-v8a/vcpkg-manifest-install.log
  Call Stack (most recent call first):
    /Users/dr.feng/Library/Android/sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
    CMakeLists.txt:20 (project)
  
  


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
29 actionable tasks: 1 executed, 28 up-to-date
cat: /home/runner/work/usc-app/usc-app/vcpkg/buildtrees/sdl2/install-arm64-android-dbg-out.log: No such file or directory
dr.feng@Mac-Studio usc-app % 


May I know how do you solve this?

**Comment by SieR-VR** [comment]
Due prebuilt application is released, close this issue.
