### ISSUE TITLE
Lua Error when starting the song

### ISSUE THREAD

**Issue by P0TATOBOY** [SieR-VR/usc-app#22]
![Screenshot_20240426_033045_Unnamed_SDVX_Clone](https://github.com/SieR-VR/usc-app/assets/70763739/67ebe3dc-3233-4ff3-92cd-53898db031a4)
i have this problem whenever i tried to play any song it pops up a Lua Error, someone said using nightfall skin will fix the problem but i dont know how to replace the textures and shaders on it without replacing the modified shader for usc android only, using the nightfall shaders doesn't work, im currently using 0.1.5 for android compatibility issue since my tablet has android 14, getting to the path folder of the game is not a big problem to me

**Comment by P0TATOBOY** [comment]
i am now on android 13 and i cant go back further to android 11 since the binary version is on 6 now and the android 11 needs is binary 1, but i rooted the tablet upon installing the android 13 and still persist the problem

**Comment by P0TATOBOY** [comment]
found a fix for it that works for android 12,13 and 14!, you need to extract the v0.1.17 latest version apk and get to the assets/usc.zip folder and extract the usc.zip,
put the usc folder contents on the same level as the .usc folder placed in, remember don't put the contents inside the .usc just create the .usc file manually and don't put the contents on there, once youve done that it should look like this 
![image](https://github.com/SieR-VR/usc-app/assets/70763739/c43b8bdc-d003-480f-bb7f-915fd3d9ea19)
also the error lua called songwheel.lua you can just get that lua file uploaded by SieR-VR, here's the link for it https://github.com/SieR-VR/usc-default-android/releases/tag/v1.3.0
and when its all done it should play the song without any errors
![image](https://github.com/SieR-VR/usc-app/assets/70763739/93e56f49-c908-4d4c-b429-cc44f2604472)

**Comment by Blobz276** [comment]
@P0TATOBOY Bro please tell me exactly how you have your files setup. I've spent the last 2 hours trying to get this to work and it simply won't open. Using android 14 but even your fix won't work. I have a feeling that I haven't been doing things right from the start. The "Installation guide" isn't really much of a guide so I'm lost here. P,ease help. Like what was your whole process to get this to work
