### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by Maritsu** [SieR-VR/usc-app#8]
![Screenshot_20220902-091907_Unnamed SDVX Clone.png](https://user-images.githubusercontent.com/66056347/188080931-7ccdec42-50b5-443f-bdd5-56809bd50374.png)  
Exact same error upon launch every time  
Samsung A52, Android 12, usc-app latest version

**Comment by SieR-VR** [comment]
Did you refer installation guide?

**Comment by Maritsu** [comment]
Yes, except I can't find a link to the skins.

**Comment by Maritsu** [comment]
Oop, fixed and resolved.

**Comment by HiLordReilo** [comment]
@Maritsu how did you get this fixed? I also have this error. Tried putting stuff in both `/sdcard/.usc/` and `/sdcard/Android/data/com.example.unnamed_sdvx_clone/files/usc`, but I get the same error anyway

**Comment by Maritsu** [comment]
Simply extracted all archives with ZArchiver to /sdcard/.usc  
Anything else than that directory won't work!

Also, have you downloaded a supported skin? @HiLordReilo

**Comment by HiLordReilo** [comment]
@Maritsu yes, I tried Default, LucidWave and Nightfall from README, but usc gave the same error for every one of them. Also tried copying these font-related files from PC, but it didn't help. I use MT Manager for all of my file operations, including work with archives

**Comment by SieR-VR** [comment]
Sorry, I was busy so I left it not working. It will be fixed until this weekend.
